defaults:
  - model: poprec

dataset: ???
dataset_path: 'data/${dataset}.txt'

train:
  batch_size: 128
  lr: 0.01
  k_eval: 10
  device: 'cpu' # 'mps'

maxlen: 200
hidden_units: 50
num_blocks: 2
num_epochs: 1000
num_heads: 1
dropout_rate: 0.2
l2_emb: 0.0
