defaults:
  - model: poprec

dataset: ???
dataset_path: 'processed/${dataset}.txt'

preprocess:
  dir: 'raw/${dataset}'
  min_num_actions: 5
  lm: 'all-MiniLM-L6-v2'
  embedding_path: 'processed/${dataset}_embeddings.npy'
  batch_size: 128
  movie_lens:
    movies: '${preprocess.dir}/movies.dat'
    ratings: '${preprocess.dir}/ratings.dat'
    prompt: "Title: {title}. Genres: {genres}."

train:
  batch_size: 128
  lr: 0.001
  k_eval: 10
  max_epochs: 10
  device: 'cuda'
  # device: 'cpu' # 'mps'
