defaults:
  - model: poprec

dataset: ???
dataset_path: 'processed/${dataset}.txt'

raw_data:
  dir: 'raw/${dataset}'
  min_num_actions: 5
  movie_lens:
    movies: '${raw_data.dir}/movies.dat'
    ratings: '${raw_data.dir}/ratings.dat'


train:
  batch_size: 128
  lr: 0.001
  k_eval: 10
  max_epochs: 10
  device: 'cuda'
  # device: 'cpu' # 'mps'
