defaults:
  - model: poprec

dataset: ???
dataset_path: 'data/${dataset}.txt'
k_eval: 10

batch_size: 512
lr: 0.001
maxlen: 200
hidden_units: 50
num_blocks: 2
num_epochs: 1000
num_heads: 1
dropout_rate: 0.2
l2_emb: 0.0
device: 'mps'
